export const LOCALE_TEXT_TH = {
    page: 'หน้า',
    to: 'ถึง',
    of: 'จาก',
    nextPage: 'หน้าถัดไป',
    lastPage: 'หน้าสุดท้าย',
    firstPage: 'หน้าแรก',
    previousPage: 'หน้าก่อนหน้า',
    loadingOoo: 'กำลังโหลด...',
    noRowsToShow: 'ไม่พบข้อมูล',
    pageSizeSelectorLabel: 'แสดงจำนวน:',
    filterOoo: 'กรองข้อมูล...',
    applyFilter: 'ค้นหา',
    resetFilter: 'ล้างค่า',
    clearFilter: 'ล้างค่า',
    cancelFilter: 'ยกเลิก',
    equals: 'ตรงกับ',
    notEqual: 'ไม่ตรงกับ',
    contains: 'มีคำว่า',
    notContains: 'ไม่มีคำว่า',
    startsWith: 'ขึ้นต้นด้วย',
    endsWith: 'ลงท้ายด้วย',
    blank: 'ว่าง',
    notBlank: 'ไม่ว่าง',
    andCondition: 'และ',
    orCondition: 'หรือ',
};